# baseURL = "http://example.org/"
# languageCode = "en-us"
# title = "Coverage Assessment"
#
# theme = "gohugo-theme-ananke"
#
# contentDir = "content"
# layoutDir = "layouts"
# publishDir = "public"
# buildDrafts = false

title = "Coverage Assessment"
baseURL = "http://bookie-colin-65501.netlify.com/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
# themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

buildDrafts = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "The last theme you'll ever need. Maybe."
  # facebook = ""
  # twitter = "https://twitter.com/GoHugoIO"
  # instagram = ""
  # youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
