baseURL = "http://example.org/"
languageCode = "en-us"
title = "Coverage Assessment"

theme = "gohugo-theme-ananke"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
